apiVersion: v1
kind: Service
metadata:
  name: kartograph-dgraph-zero
  labels:
    component: dgraph-zero
spec:
  selector:
    pod: kartograph-dgraph-zero
  ports:
    - name: grpc
      port: 5080
      targetPort: 5080
      protocol: TCP
    - name: http
      port: 6080
      targetPort: 6080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kartograph-dgraph-alpha
  labels:
    component: dgraph-alpha
spec:
  selector:
    pod: kartograph-dgraph-alpha
  ports:
    - name: grpc
      port: 7080
      targetPort: 7080
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc-internal
      port: 9080
      targetPort: 9080
      protocol: TCP
