/**
 * Changelog data for What's New dialog
 * This file is auto-generated by scripts/generate-changelog.js at build time
 * DO NOT EDIT MANUALLY
 */

export interface ChangelogData {
  features: string[];
  improvements: string[];
  bugFixes: string[];
}

export const changelog: ChangelogData = {
  "features": [],
  "improvements": [],
  "bugFixes": [
    "Correct ArgoCD repo URL to openshift-hyperfleet org (#4)"
  ]
};

export default changelog;
