---
# SecretProviderClass for Better Auth secret
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kartograph-auth-vault  # pragma: allowlist secret
spec:
  provider: vault
  # Sync to Kubernetes Secret so we can use as env vars
  secretObjects:
    - secretName: kartograph-secrets  # pragma: allowlist secret
      type: Opaque
      data:
        - objectName: auth-secret  # pragma: allowlist secret
          key: auth-secret  # pragma: allowlist secret
  parameters:
    vaultAddress: "https://vault.corp.redhat.com"
    roleName: "kartograph-stage"
    objects: |
      - objectName: "auth-secret"  # pragma: allowlist secret
        secretPath: "hcm-ai/data/kartograph/stage/better-auth"
        secretKey: "BETTER_AUTH_SECRET"  # pragma: allowlist secret
---
# SecretProviderClass for GitHub OAuth
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kartograph-github-oauth-vault  # pragma: allowlist secret
spec:
  provider: vault
  secretObjects:
    - secretName: kartograph-github-oauth  # pragma: allowlist secret
      type: Opaque
      data:
        - objectName: github-client-id
          key: client-id
        - objectName: github-client-secret  # pragma: allowlist secret
          key: client-secret  # pragma: allowlist secret
  parameters:
    vaultAddress: "https://vault.corp.redhat.com"
    roleName: "kartograph-stage"
    objects: |
      - objectName: "github-client-id"
        secretPath: "hcm-ai/data/kartograph/stage/github-oidc"
        secretKey: "GITHUB_CLIENT_ID"
      - objectName: "github-client-secret"
        secretPath: "hcm-ai/data/kartograph/stage/github-oidc"
        secretKey: "GITHUB_CLIENT_SECRET"  # pragma: allowlist secret
---
# SecretProviderClass for Vertex AI credentials
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kartograph-vertex-ai-vault  # pragma: allowlist secret
spec:
  provider: vault
  secretObjects:
    - secretName: kartograph-vertex-ai  # pragma: allowlist secret
      type: Opaque
      data:
        - objectName: vertex-credentials-json
          key: credentials.json
        - objectName: vertex-project-id
          key: project-id
        - objectName: vertex-region
          key: region
  parameters:
    vaultAddress: "https://vault.corp.redhat.com"
    roleName: "kartograph-stage"
    objects: |
      - objectName: "vertex-credentials-json"
        secretPath: "hcm-ai/data/kartograph/stage/vertex-ai"
        secretKey: "credentials.json"
      - objectName: "vertex-project-id"
        secretPath: "hcm-ai/data/kartograph/stage/vertex-ai"
        secretKey: "VERTEX_PROJECT_ID"
      - objectName: "vertex-region"
        secretPath: "hcm-ai/data/kartograph/stage/vertex-ai"
        secretKey: "VERTEX_REGION"
